%% Import data from text file
% Script for importing data from the following text file:
%
%    filename: C:\Users\drewj\Documents\atom\positions.txt
%
% Auto-generated by MATLAB on 09-Apr-2021 15:36:57

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 2);

% Specify range and delimiter
opts.DataLines = [1, Inf];
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["VarName1", "VarName2"];
opts.VariableTypes = ["double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, ["VarName1", "VarName2"], "TrimNonNumeric", true);
opts = setvaropts(opts, ["VarName1", "VarName2"], "ThousandsSeparator", ",");

% Import the data
tbl = readtable("C:\Users\drewj\Documents\atom\positions.txt", opts);

%% Convert to output type
posx = tbl.VarName1;
posy = tbl.VarName2;

%% Clear temporary variables
clear opts tbl